FROM overv/openstreetmap-tile-server
MAINTAINER magno.mabreu@gmail.com

ENV ftp_proxy="http://07912470743:da030801@proxy-1dn.mb:6060/"
ENV http_proxy="http://07912470743:da030801@proxy-1dn.mb:6060/"
ENV https_proxy="http://07912470743:da030801@proxy-1dn.mb:6060/"