{
 "title": "Spring Boot 1.x",
 "description": "Dashboard for Spring Boot 1.x apps using Micrometer and Prometheus",
 "tags": [
  "java",
  "spring",
  "spring boot",
  "prometheus",
  "tomcat",
  "micrometer",
  "jvm"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Prometheus Job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Guardiao",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "guardiao_sessoes_ativas",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Sessoes Ativas",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Mean response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"$job\"}[5m])/rate(http_server_requests_seconds_count{job=\"$job\"}[5m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Errors in logs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max_over_time(logback_events_total{job=\"guardiao\", level=\"error\"}[1h])"
    }
   ]
  },
  {
   "title": "Warnings in logs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max_over_time(logback_events_total{job=\"$job\", level=\"warn\"}[1h])"
    }
   ]
  },
  { "title": "API stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"$job\"}[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Top 10 APIs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{job=\"$job\"}[1m])))"
    }
   ]
  },
  { "title": "Tomcat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Requests duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"$job\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{job=\"$job\", status!~\"5..\"}[1m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(http_server_requests_seconds_max{job=\"$job\", status!~\"5..\"})",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$job\", status=~\"5..\"}[1m]))",
     "legendFormat": "5xx - Server Errors"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$job\", status=~\"4..\"}[1m]))",
     "legendFormat": "4xx - Client Errors"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$job\", status=~\"2..\"}[1m]))",
     "legendFormat": "2xx - Success"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$job\", status=~\"3..\"}[1m]))",
     "legendFormat": "3xx - Redirections"
    }
   ]
  },
  {
   "title": "Tomcat - Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tomcat_threads_busy{job=\"$job\"})",
     "legendFormat": "Busy"
    },
    {
     "expr": "sum(tomcat_threads_current{job=\"$job\"})",
     "legendFormat": "In Use"
    },
    {
     "expr": "sum(tomcat_threads_config_max{job=\"$job\"})",
     "legendFormat": "Max Available"
    }
   ]
  },
  { "title": "JVM - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Free memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 33 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100-(sum(jvm_memory_used_bytes{job=\"$job\"})*100/sum(jvm_memory_max_bytes{job=\"$job\"}))"
    }
   ]
  },
  {
   "title": "JVM Memory - Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$job\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$job\"})",
     "legendFormat": "max"
    },
    {
     "expr": "process_memory_rss_bytes{job=\"$job\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_memory_pss_bytes{job=\"$job\"}",
     "legendFormat": "pss"
    },
    {
     "expr": "process_memory_swap_bytes{job=\"$job\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_swappss_bytes{job=\"$job\"}",
     "legendFormat": "swappss"
    },
    {
     "expr": "process_memory_pss_bytes{job=\"$job\"} + process_memory_swap_bytes{job=\"$job\"}",
     "legendFormat": "phys (pss+swap)"
    }
   ]
  },
  {
   "title": "Free Heap",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 41 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100-(sum(jvm_memory_used_bytes{job=\"$job\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{job=\"$job\", area=\"heap\"}))"
    }
   ]
  },
  {
   "title": "Free Non-Heap",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 41 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100-(sum(jvm_memory_used_bytes{job=\"$job\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{job=\"$job\", area=\"nonheap\"}))"
    }
   ]
  },
  {
   "title": "JVM Memory - Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$job\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Memory - Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$job\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM - Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{job=\"$job\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{job=\"$job\"}[1m])/rate(jvm_gc_pause_seconds_count{job=\"$job\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{job=\"$job\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{job=\"$job\"}[1m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{job=\"$job\"}[1m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  { "title": "JVM - Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"$job\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{job=\"$job\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{job=\"$job\"}",
     "legendFormat": "System load average"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live{job=\"$job\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{job=\"$job\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{job=\"$job\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_max_fds{job=\"$job\"}",
     "legendFormat": "max"
    },
    {
     "expr": "process_files_open{job=\"$job\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max{job=\"$job\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}