global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'sisgide'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['cadvisor:8080','prometheus:9090','grafana:3000','node-exporter:9100']
