{
 "title": "[SisGEODEF] Docker",
 "tags": [
  "docker",
  "sisgeodef"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 0 },
   "content": "<h1><br><img src=\"https://www.defesa.gov.br/arquivos/2016/mes10/logo_ministerio_da_defesa_md_positivo.png\" class=\"center\" height=\"60\"></h1>"
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 1, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"node-exporter:9100\",job=\"sisgide\"} - node_boot_time_seconds{instance=\"node-exporter:9100\",job=\"sisgide\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"sisgide\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\",job=\"sisgide\"}"
    }
   ]
  },
  {
   "title": "/",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"node-exporter:9100\",job=\"sisgide\",device=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "/srv",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "687194767360" }
   ]
  },
  {
   "title": "/swap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"node-exporter:9100\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[1d]))"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "node_procs_running" }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"sisgide\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"node-exporter:9100\",job=\"sisgide\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"sisgide\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Disk space (/)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{fstype=\"xfs\",instance=\"node-exporter:9100\"} - node_filesystem_free_bytes{fstype=\"xfs\",instance=\"node-exporter:9100\"} )/ node_filesystem_size_bytes{fstype=\"xfs\",instance=\"node-exporter:9100\"})"
    }
   ]
  },
  {
   "title": "Disk space (/srv)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min((687194767360 - container_fs_usage_bytes {device=\"/dev/mapper/srv-dados\"}) / 687194767360)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"} - node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\"}) / node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"}) * 100"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"node-exporter:9100\"} - node_memory_SwapFree_bytes{instance=\"node-exporter:9100\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[1d])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"node-exporter:9100\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{instance=\"node-exporter:9100\"}))"
    }
   ]
  },
  {
   "title": "Used Disk Space (/srv)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "687194767360 - container_fs_usage_bytes {device=\"/dev/mapper/srv-dados\"}",
     "legendFormat": "Used Disk Space"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(node_disk_read_bytes_total[1d])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[1d])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"} - node_memory_MemFree_bytes{instance=\"node-exporter:9100\"} - node_memory_Cached_bytes{instance=\"node-exporter:9100\"} - node_memory_Buffers_bytes{instance=\"node-exporter:9100\"} - node_memory_Slab_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"node-exporter:9100\"} + node_memory_Slab_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "Buffers"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[1d])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[1d])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[1d])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Usage memory",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1d])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1d])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}