FROM kartoza/postgis:11.5-2.8
MAINTAINER magno.mabreu@gmail.com

RUN apt-get update && apt-get install -y --no-install-recommends build-essential make cmake g++ libboost-dev libboost-system-dev \
libboost-filesystem-dev libexpat1-dev zlib1g-dev libbz2-dev libpq-dev libproj-dev lua5.2 liblua5.2-dev \
wget software-properties-common python3-setuptools python3-matplotlib python3-bs4 python3-numpy python3-gdal osmium-tool curl gdal-bin


